#!/usr/bin/env bash

# See `env/duplicate_exe_outputs.src` for explanation.

${WIN_DUPEBIN_CC-$CC} "$@" || exit $?

path=

while [[ $# -gt 0 ]]; do
  case $1 in
    -o)
      path="$2"
      shift
      shift
      ;;
    -c|-shared|--shared|-fsyntax-only|-E|-S)
      exit
      ;;
    *)
      shift
      ;;
  esac
done

if [[ ! $path ]]; then
    cp -f "a.exe" "a.out"
    exit
fi

[[ $path != *.* ]] && path="$path.exe"
if [[ $path == *.exe ]]; then
    cp -f "$path" "${path%.exe}"
fi
