#!/bin/bash

if [[ -v WIN_NATIVE_WINDRES ]]; then
"$WIN_NATIVE_WINDRES" "--include=$MSYSTEM_PREFIX/include" "$@"
else
# Even CLANG64 environment has a copy of windres with this name.
wine windres.exe "$@"
fi
